export const sheets = {
    MAP_STYLES: 'map-styles-sheet',
    MAP_PACKS: 'map-packs-sheet',
    MAP_SEARCH: 'map-search-sheet',
    MAP_PACKS_SEARCH: 'map-packs-search-sheet',
    MAP_MARKER: 'map-marker-sheet',
    BUILDER_AREA_CREATE_EDIT: 'builder-area-create-edit-sheet',
    BUILDER_MAP_PACKS: 'builder-map-packs-sheet',
    PINS_EDIT_OPTIONS: 'pins-edit-options',
    MAP_PACKS_SAVED_PACKS: 'map-pack-saved-packs',
    SAVED_OPTIONS: 'saved-options',
    MAP_PACK_GROUP_OPTIONS: 'map-pack-group-options',
    MAP_POI_SHEET: 'map-point-of-interest',
    ROUTES_EDIT_OPTIONS: 'routes-edit-options',
}